INSERT INTO users(name, email, age) VALUES ('UserName', 'UserEmail', 20)
INSERT INTO users(name, email, age) VALUES ('NameUser', 'UserEmail', 30)
INSERT INTO diaries(user_id, description, date) VALUES (1, 'Test Description', '2019-04-03')
INSERT INTO diaries(user_id, description, date) VALUES (1, 'Test Description 2', '2019-04-03')
INSERT INTO forum_questions(user_id, question_title, question, category, date) VALUES (1, 'Test Title', 'Test Question', 'Test Category', '2019-04-03')
INSERT INTO forum_questions(user_id, question_title, question, category, date) VALUES (1, 'Test Title-2', 'Test Question-2', 'Test Category-2', '2010-02-01')

INSERT INTO forum_answers(user_id, question_id, answer, date) VALUES (1, 1, 'Test Answer', '2021-04-25')
INSERT INTO forum_answers(user_id, question_id, answer, date) VALUES (1, 1, 'Test Answer2', '2021-04-26')
INSERT INTO pregnancy_info(user_id, number_of_children, due_date, kicks_count, status) VALUES (1, 1, 01012020, 1, true)
INSERT INTO weights_during_pregnancy(pregnancy_info_id, date, weight) VALUES (1, '2021-04-25', 60)
INSERT INTO tasks_after_birth(user_id, task_status, task_name, task_text) VALUES (1, false, 'Test Task Name', 'Test Task Text')
INSERT INTO tasks_before_birth(user_id, task_status, task_name, task_text) VALUES (1, false, 'Test Task Name', 'Test Task Text')
INSERT INTO kids(parent_id, first_name, last_name, sex, birth_date, weight, height) VALUES (1, 'Test Name', 'Test Last Name', 'Male', 01012020, 3, 50)
INSERT INTO feedings(user_id, kid_id, date, feeding_type, time, quantity) VALUES (1, 1, 01012000, 'Bottle', 0900, 100)
INSERT INTO tips(title, text, date) VALUES ('Tip Test Title 1', 'Tip Test Text 1', '2021-04-25')
INSERT INTO tips(title, text, date) VALUES ('Tip Test Title 2', 'Tip Test Text 2', '2021-04-26')

INSERT INTO question_likes(user_id, question_id, value) VALUES (1, 1, true)
INSERT INTO question_likes(user_id, question_id, value) VALUES (2, 2, false)
INSERT INTO answer_likes(user_id, answer_id, value) VALUES (1, 1, true)
INSERT INTO answer_likes(user_id, answer_id, value) VALUES (2, 2, false)

INSERT INTO blog_articles(category, date, text, title) VALUES ('mom', '2019-04-03', 'test text', 'test title')
INSERT INTO blog_articles(category, date, text, title) VALUES ('mom', '2019-04-05', 'test text-1', 'test title-2')
INSERT INTO blog_articles(category, date, text, title) VALUES ('dad', '2019-04-06', 'test text-3', 'test title-3')
INSERT INTO blog_articles(category, date, text, title) VALUES ('dad', '2019-04-07', 'test text-4', 'test title-4')

INSERT INTO food(recipe_name, recipe_text, meal_time) VALUES ('Burger', 'Insert meat between bread', 'Lunch')
INSERT INTO food(recipe_name, recipe_text, meal_time) VALUES ('Spaghetti', 'Mix pasta with sauce in a blender', 'Lunch')
INSERT INTO food(recipe_name, recipe_text, meal_time) VALUES ('Oatmeal', 'Mix Oat with milk', 'Breakfast')
INSERT INTO food(recipe_name, recipe_text, meal_time) VALUES ('Toast', 'Bread + cheese + ham', 'Breakfast')
INSERT INTO food(recipe_name, recipe_text, meal_time) VALUES ('Kabanos', 'Just open and fruu', '2nd Breakfast')

